server:
  port: 8080 # 访问端口

spring:
  datasource:
    dynamic:
      primary: db1   #设置默认的数据源
      datasource:
        db1:
          username: root
          password: 123456
          url: jdbc:mysql://localhost:3306/zq_blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
        db2:
          username: root
          password: 123456
          url: jdbc:mysql://localhost:3306/zq_blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
      mp-enabled: true
logging:
  level:
    com.xkcoding.multi.datasource.mybatis: debug